### ISSUE TITLE
希望Copiers能提供一个清除ClassMap接口

### ISSUE THREAD

**Issue by liangGTY** [drtrang/Copiers#3]
当我想对同一对POJO对象进行映射时，第二次会复用第一次的缓存，但是这并不是我想要的

**Comment by drtrang** [comment]
能说下具体场景吗？什么情况下想清除缓存重新建立绑定关系

**Comment by liangGTY** [comment]
有一个折线图类，和一个包含各项业务数据指标的DTO的时候，会想把某一项指标数据映射到y轴。这种时候就会存在多次映射

**Comment by drtrang** [comment]
我考虑了一下，最终的实现方式可能是增加一个 `name` 参数，支持 Source Class 和 Target Class 之间的多次映射，举例如下：
```java
Copier<User, UserEntity> copier = Copiers.createMapper(User.class, UserEntity.class)
                .name("skip-age")
                .skip("age")
                .register();

Copier<User, UserEntity> copier2 = Copiers.createMapper(User.class, UserEntity.class)
                .name("all-filed")
                .register();
```

不过最近工作比较忙，而且需要更改 EasyMapper 的源码，近期可能没办法迭代。

**Comment by neoremind** [comment]
因为每次建立User.class到UserEntity.class的转换都是比较费时的，需要反射以及很多的解析工作，即使是使用的高性能的字节码工具，可能仍然会有一定的开销，如果真的需要我可以全局开一个口子，如果存在某个环境变量我就不缓存，强制重新建立关系。

另外看你的需求，感觉是A，B，C，D... 很多映射到DTO的场景，这个需求还真不太多见，一般是一对一的，你的多对1，其实需要封装一个facade或者transformer做比较合适，如果hard code的工作不太多，其实也可以的。

**Comment by liangGTY** [comment]
嗯，我目前的解决方案就是transformer。但是我觉得drtrang的思路很不错，可以自定义映射关系的key，而不是强制的class-class形式key，这样灵活性更好

**Comment by neoremind** [comment]
这样是可行的，最近工作比较忙，暂时没时间踏实enhance，列入TBD的feature当中，当然如果可以的话欢迎提PR。
